version: '3'

services:
  caddy:
    container_name: wpdock-web
    depends_on:
      - php
    image: caddy
    ports:
      - 443:443
    volumes:
      - ./src:/srv/app
      - ./Caddyfile:/etc/caddy/Caddyfile
  composer:
    container_name: wpdock-deps
    image: composer:2
    volumes:
      - ./src:/app
    command: install --ignore-platform-reqs --no-interaction

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wpdock-app
    image: php:fpm
    volumes:
      - ./src:/srv/app

volumes:
  vendor:
